import type { Property, Agent } from "./types"

export const agents: Agent[] = [
  {
    id: "1",
    name: "María González",
    avatar: "https://i.postimg.cc/DzxYnSnG/pexels-olly-845457.jpg",
    phone: "+504 9876-5432",
    email: "maria@inmobiliaria.com",
  },
  {
    id: "2",
    name: "Carlos Rodríguez",
    avatar: "https://i.postimg.cc/R0Sbk759/pexels-ahmedadly-1270184.jpg",
    phone: "+504 9876-5433",
    email: "carlos@inmobiliaria.com",
  },
  {
    id: "3",
    name: "Ana Martínez",
    avatar: "https://i.postimg.cc/4xbS280B/pexels-moh-adbelghaffar-783941.jpg",
    phone: "+504 9876-5434",
    email: "ana@inmobiliaria.com",
  },
]

export const properties: Property[] = [
  {
    id: "1",
    title: "Casa Moderna en Zona Residencial",
    description:
      "Hermosa casa de dos plantas con acabados de lujo, jardín amplio y ubicación privilegiada en zona residencial exclusiva.",
    images: [
      "https://i.postimg.cc/MKB7pCZp/pexels-binyaminmellish-1396122.jpg",
      "https://i.postimg.cc/Hk4bQbyG/pexels-magda-ehlers-pexels-772177.jpg",
      "https://i.postimg.cc/gcQydzW7/pexels-pixasquare-1115804.jpg",
    ],
    city: "Tegucigalpa",
    price: 4500000,
    type: "casa",
    status: "venta",
    dimensions: 250,
    bedrooms: 4,
    bathrooms: 3,
    garage: true,
    amenities: ["Jardín", "Piscina", "Terraza", "Cocina equipada"],
    coordinates: { lat: 14.0723, lng: -87.1921 },
    agent: agents[0],
  },
  {
    id: "2",
    title: "Apartamento Céntrico",
    description: "Moderno apartamento en el centro de la ciudad, completamente amueblado y listo para habitar.",
    images: [
      "https://i.postimg.cc/8cJhW3hw/pexels-tobiasbjorkli-2119714.jpg",
      "https://i.postimg.cc/gcQydzW7/pexels-pixasquare-1115804.jpg",
    ],
    city: "San Pedro Sula",
    price: 25000,
    type: "apartamento",
    status: "alquiler",
    dimensions: 85,
    bedrooms: 2,
    bathrooms: 1,
    garage: false,
    amenities: ["Amueblado", "Aire acondicionado", "Balcón"],
    coordinates: { lat: 15.5044, lng: -88.0251 },
    agent: agents[1],
  },
  {
    id: "3",
    title: "Terreno para Desarrollo",
    description: "Excelente terreno para desarrollo inmobiliario en zona de alta plusvalía.",
    images: [
      "https://i.postimg.cc/qvC50bSs/pexels-petra-nesti-1766376-32981969.jpg",
      "https://i.postimg.cc/zfZPfwY9/pexels-simonmigaj-762064.jpg",
    ],
    city: "La Ceiba",
    price: 1800000,
    type: "terreno",
    status: "venta",
    dimensions: 1000,
    amenities: ["Servicios básicos", "Acceso pavimentado"],
    coordinates: { lat: 15.7597, lng: -86.7822 },
    agent: agents[2],
  },
  {
    id: "4",
    title: "Casa de Campo",
    description: "Acogedora casa de campo con vistas panorámicas y amplio terreno.",
    images: [
      "https://i.postimg.cc/MKB7pCZp/pexels-binyaminmellish-1396122.jpg",
      "https://i.postimg.cc/Hk4bQbyG/pexels-magda-ehlers-pexels-772177.jpg",
    ],
    city: "Comayagua",
    price: 3200000,
    type: "casa",
    status: "venta",
    dimensions: 180,
    bedrooms: 3,
    bathrooms: 2,
    garage: true,
    amenities: ["Chimenea", "Huerto", "Pozo de agua"],
    coordinates: { lat: 14.4602, lng: -87.6445 },
    agent: agents[0],
  },
  {
    id: "5",
    title: "Apartamento de Lujo",
    description: "Exclusivo apartamento con acabados premium y vistas panorámicas.",
    images: [
      "https://i.postimg.cc/8cJhW3hw/pexels-tobiasbjorkli-2119714.jpg",
      "https://i.postimg.cc/gcQydzW7/pexels-pixasquare-1115804.jpg",
      "https://i.postimg.cc/Hk4bQbyG/pexels-magda-ehlers-pexels-772177.jpg",
    ],
    city: "San Pedro Sula",
    price: 45000,
    type: "apartamento",
    status: "alquiler",
    dimensions: 120,
    bedrooms: 3,
    bathrooms: 2,
    garage: true,
    amenities: ["Vista panorámica", "Gimnasio", "Piscina", "Portero"],
    coordinates: { lat: 15.5044, lng: -88.0251 },
    agent: agents[1],
  },
  {
    id: "6",
    title: "Terreno Comercial",
    description: "Amplio terreno ideal para desarrollo comercial en zona estratégica.",
    images: [
      "https://i.postimg.cc/9XrsXY4Q/pexels-hson-32993569.jpg",
      "https://i.postimg.cc/8k997fWB/pexels-mark-direen-622749-32984691.jpg",
    ],
    city: "Tegucigalpa",
    price: 2500000,
    type: "terreno",
    status: "venta",
    dimensions: 1500,
    amenities: ["Ubicación comercial", "Fácil acceso", "Servicios completos"],
    coordinates: { lat: 14.0723, lng: -87.1921 },
    agent: agents[2],
  },
]

export const cities = [...new Set(properties.map((p) => p.city))]
export const propertyTypes = ["casa", "apartamento", "terreno"]
export const statusOptions = ["venta", "alquiler"]
